# Site settings
title: Houses of Stones
url: http://housesofstones.github.io
name: Houses of Stones
description: '&quot;Science is facts; just as houses are made of stones, so is science made of facts; but a pile of stones is not a house and a collection of facts is not necessarily science.&quot;              – Henri Poincare'

# Build settings
markdown: kramdown
highlighter: pygments

